"""initial schema

Revision ID: 499df124434b
Revises: 
Create Date: 2026-08-11 01:27:29.178316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499df124434b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('services_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owners_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('diff_hash', sa.String(length=64), nullable=True),
    sa.Column('pr_title', sa.String(length=512), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=True),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_repo_id'), 'analyses', ['repo_id'], unique=False)
    op.create_index('ix_analyses_status', 'analyses', ['status'], unique=False)
    op.create_table('file_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('is_shared_package', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', name='uq_file_nodes_repo_path')
    )
    op.create_index(op.f('ix_file_nodes_repo_id'), 'file_nodes', ['repo_id'], unique=False)
    op.create_table('incident_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_chunks_incident_id'), 'incident_chunks', ['incident_id'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_file_id'), 'code_chunks', ['file_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('src_file_id', sa.UUID(), nullable=False),
    sa.Column('dst_file_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dst_file_id'], ['file_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_file_id'], ['file_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edges_repo_dst_file_id', 'edges', ['repo_id', 'dst_file_id'], unique=False)
    op.create_index(op.f('ix_edges_repo_id'), 'edges', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_repo_id'), table_name='edges')
    op.drop_index('ix_edges_repo_dst_file_id', table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_code_chunks_file_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_incident_chunks_incident_id'), table_name='incident_chunks')
    op.drop_table('incident_chunks')
    op.drop_index(op.f('ix_file_nodes_repo_id'), table_name='file_nodes')
    op.drop_table('file_nodes')
    op.drop_index('ix_analyses_status', table_name='analyses')
    op.drop_index(op.f('ix_analyses_repo_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('repos')
    op.drop_table('incidents')
    # ### end Alembic commands ###
